version: '2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana

  containerexporter:
    image: prom/container-exporter
    container_name: containerexporter
    ports:
      - 9104:9104
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/cgroup

  prometheus:
    image: prom/prometheus:v1.7.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /opt/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    depends_on:
      - containerexporter

networks:
  monitoring:
volumes:
  grafana-volume:

